import turtle
wn=turtle.Screen()
t1=turtle.Turtle()
def giyuk(size):
    t1.fd(size)
    t1.right(90)
    t1.fd(size)

    
turnBy=45
size=100
oldPos=t1.pos()
oldHead=t1.heading()
giyuk(100)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+turnBy)
t1.pendown()
giyuk(100)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+turnBy * 2)
t1.pendown()
giyuk(100)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+turnBy * 3)
t1.pendown()
giyuk(100)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+turnBy * 4)
t1.pendown()
giyuk(100)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+turnBy * 5)
t1.pendown()
giyuk(100)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+turnBy * 6)
t1.pendown()
giyuk(100)
t1.penup()
t1.setpos(oldPos)
t1.setheading(oldHead+turnBy * 7)
t1.pendown()
giyuk(100)
